# Generated by Django 4.2 on 2023-07-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('pasport_ser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelgan_sana', models.DateField()),
                ('ketish_sana', models.DateField(blank=True, null=True)),
                ('yotgan_kun_soni', models.PositiveSmallIntegerField(default=1)),
                ('qarovchi', models.BooleanField(default=False)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bemor')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveSmallIntegerField()),
                ('tolangan_summa', models.PositiveSmallIntegerField()),
                ('tolandi', models.BooleanField(default=False)),
                ('haqdor', models.BooleanField(default=False)),
                ('sana', models.DateField(blank=True, null=True)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bemor')),
                ('joylashtirish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.joylashtirish')),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.CharField(max_length=50)),
                ('raqam', models.PositiveSmallIntegerField()),
                ('narx', models.FloatField()),
                ('bosh_joy_soni', models.PositiveSmallIntegerField()),
                ('sigim', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yollanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('xona', models.PositiveSmallIntegerField()),
                ('narx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Xulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateField(blank=True, null=True)),
                ('holat', models.CharField(max_length=50)),
                ('tolov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tolov')),
            ],
        ),
        migrations.AddField(
            model_name='tolov',
            name='yollanma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.yollanma'),
        ),
        migrations.AddField(
            model_name='joylashtirish',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.xona'),
        ),
    ]
